version: "3.5"

services:
  app_build:
    build: ../
    container_name: "app_build"
    volumes:
      - dist:/usr/src/app/dist

  app_web:
    image: nginx
    ports:
      - 8123:80
    container_name: "app_web"
    restart: unless-stopped
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  dist: